const XS_BREAKPOINT = 320;
const SM_BREAKPOINT = 480;
const MD_BREAKPOINT = 720;
const LG_BREAKPOINT = 1110;
const XL_BREAKPOINT = 1440;

export {
  XS_BREAKPOINT,
  SM_BREAKPOINT,
  MD_BREAKPOINT,
  LG_BREAKPOINT,
  XL_BREAKPOINT,
};
