const BLACK_COLOR = '#000000';
const WHITE_COLOR = '#FFFFFF';
const TORY_BLUE_COLOR = '#344090';
const NIGHT_RIDER_COLOR = '#333333';
const GREY_COLOR = '#797979';
const VIKING_COLOR = '#46BFC9';
const RHINO_COLOR = '#444C57';
const BALTIC_SEA_COLOR = '#323941';
const SUMMER_SKY_COLOR = '#2EA7E0';
const CURIOUS_BLUE = '#2C90CA';
const CURIOUS_BLUE_BLUR = '#2C90CAB3';
const CERULEAN = '#006298';
const WHISPER_COLOR = '#EBEBEB';
const ECLIPSE_COLOR = '#3B3B3B';
const RED_COLOR = '#f73378';
const ARAPAWA_COLOR = '#31505E';
const BUSYELLOW_COLOR = '#FDDD38';
const MISCHKA_COLOR = '#AEB2B7';
const PURE_WHITE = 'rgb(247, 248, 250)';
const LIGHT_GREY = '#e9ecef';
export {
  BLACK_COLOR,
  WHITE_COLOR,
  TORY_BLUE_COLOR,
  NIGHT_RIDER_COLOR,
  GREY_COLOR,
  VIKING_COLOR,
  RHINO_COLOR,
  BALTIC_SEA_COLOR,
  SUMMER_SKY_COLOR,
  CURIOUS_BLUE,
  CURIOUS_BLUE_BLUR,
  CERULEAN,
  WHISPER_COLOR,
  ECLIPSE_COLOR,
  RED_COLOR,
  ARAPAWA_COLOR,
  BUSYELLOW_COLOR,
  MISCHKA_COLOR,
  PURE_WHITE,
  LIGHT_GREY,
};
